[package]
name = "libpath"
version.workspace = true
edition.workspace = true

[dependencies]
tracing.workspace = true
dirs = "6.0.0"
libproduct = { version = "0.0.1", path = "../libproduct" }

[lints]
workspace = true
